In [1]:
import pandas as pd

In [2]:
eligible = pd.read_csv('../../data/FF4_Eligibility_CALCULATED.csv')

In [3]:
eligible.head()

,Player,Discord Name,Twitch Name,FF1 Placing,FF2 Placing,BB1 Placing,FF3 Placing,BB2 Placing,eligible,reason
0,_teejaay_,_teejaay_,teejaay1311,-1.0,-1.0,5.0,-1,-1,No,Bracket finalist in BB1 (Placed #5)
1,3ps1l0,3ps1l0n,3ps1l0,17.0,33.0,-1.0,33,-1,No,"Played in FF1, FF2, and FF3"
2,55Spyder,55Spyder,55Spyder,-1.0,79.0,-1.0,66,-1,Yes,Eligible for FF4
3,8bitmaster_,8bitmaster_,8bitmaster_,-1.0,79.0,-1.0,-1,-1,Yes,Eligible for FF4
4,a_Press,a_press,a_Press,5.0,-1.0,-1.0,-1,-1,No,Top 16 in FF1 (Placed #5)

In [4]:
eligible[eligible['eligible'] == 'Yes']

,Player,Discord Name,Twitch Name,FF1 Placing,FF2 Placing,BB1 Placing,FF3 Placing,BB2 Placing,eligible,reason
2,55Spyder,55Spyder,55Spyder,-1.0,79.0,-1.0,66,-1,Yes,Eligible for FF4
3,8bitmaster_,8bitmaster_,8bitmaster_,-1.0,79.0,-1.0,-1,-1,Yes,Eligible for FF4
5,aBrinkk,abrinkk,aBrinkk,17.0,33.0,9.0,-1,-1,Yes,Eligible for FF4
6,Adam_OWA,adam_owa,adam_owa,-1.0,33.0,-1.0,-1,-1,Yes,Eligible for FF4
7,AlistorTheWolf,alistorthewolf,AlistorTheWolf,-1.0,-1.0,-1.0,66,-1,Yes,Eligible for FF4
...,...,...,...,...,...,...,...,...,...,...
256,Xuio,xuio,Xuio007,-1.0,-1.0,-1.0,66,-1,Yes,Eligible for FF4
257,Yang,yangerzone,Out_With_A_Yang_,-1.0,-1.0,-1.0,66,-1,Yes,Eligible for FF4
259,zero_probability,zero_probability,Zero_Probability,-1.0,17.0,-1.0,-1,-1,Yes,Eligible for FF4
260,Zojalyx,zojalyx,Zojalyx,-1.0,33.0,17.0,-1,-1,Yes,Eligible for FF4
261,Zyren,zyren75,zyren_x,-1.0,-1.0,-1.0,66,9,Yes,Eligible for FF4

In [6]:
eligible[eligible['eligible'] == 'Yes']["Player"].to_csv('../../data/FF4_Eligibility_CALCULATED_ELIGIBLE.csv', index=False)